settings:
  title: 'Status Page'
  url: 'https://status-page.eidam.dev' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: workers-cloudflare-com # unique identifier
    name: workers.cloudflare.com
    description: 'You write code. They handle the rest.' # default=empty
    url: 'https://workers.cloudflare.com/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false 
    linkable: false # allows the title to be a link, default=true 

  - id: cloudflare
    name: www.cloudflare.com
    description: 'Built for anything connected to the Internet.' 
    url: 'https://www.cloudflare.com'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true

  - id: blog-cloudflare-com  
    name: The Cloudflare Blog
    url: 'https://blog.cloudflare.com/'
    method: GET
    expectStatus: 200

  - id: OpenAI   
    name: OpenAI 
    url: 'https://chat.openai.com'  
    method: GET
    expectStatus: 200

  - id: xyhelper    
    name: xyhelper  
    description: 'xyhelper镜像网站'    
    url: 'https://ttzi.top'   
    method: GET
    expectStatus: 200  

  - id: coze-bot.onrender.com  
    name: coze-bot.onrender.com  
    description: 'coze discord proxy'  
    url: 'https://coze-bot.onrender.com' 
    method: GET
    expectStatus: 200

  - id: One-Api   
    name: One-Api  
    description: 'one api'    
    url: 'https://one-api-3zrb.onrender.com'  
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true
    
  - id: notion  
    name: notion 
    description: 'notion个人博客'  
    url: 'https://notion.qipusong.store'  
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true
    
